#!/bin/bash
# 06_run_classifier_training.sh
#
# Train an in-house naive Bayes taxonomic classifier on the SILVA 138
# reference database, restricted to the V3-V4 region by extracting reads
# with the SAME primer pair used to amplify and trim the tick specimens'
# own reads (341F/806R) -- per Methods (corrected): "The classifier was
# trained in-house using the QIIME 2 feature-classifier plugin: reference
# sequences were extracted from the full-length SILVA 138 database with
# extract-reads, using the same primer pair used for PCR amplification of
# the tick specimens, 341F and 806R, and a naive Bayes classifier was
# then fitted to the extracted reference reads and their corresponding
# taxonomy with fit-classifier-naive-bayes."
#
# Requires the raw SILVA 138 99% OTU reference files
# (CLASSIFIER_RAW_SEQS / CLASSIFIER_RAW_TAX in config.sh) to already be
# present in CLASSIFIER_DIR -- these are large reference artifacts
# downloaded separately (not generated by this pipeline), so this script
# does not attempt to fetch them.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../config.sh"

if [[ ! -f "$CLASSIFIER_RAW_SEQS" || ! -f "$CLASSIFIER_RAW_TAX" ]]; then
  echo "ERROR: raw SILVA 138 reference files not found:" >&2
  echo "  $CLASSIFIER_RAW_SEQS" >&2
  echo "  $CLASSIFIER_RAW_TAX" >&2
  exit 1
fi

mkdir -p "$CLASSIFIER_DIR"
extracted_reads="$CLASSIFIER_DIR/silva-138-99-seqs-341F-806R.qza"

echo "qiime2 version: $(qiime --version 2>&1 | head -1)"
echo "PRIMER_F=$PRIMER_F"
echo "PRIMER_R=$PRIMER_R"

echo "Step 1/2: Extracting V3-V4 reference reads (341F/806R) from SILVA 138..."
qiime feature-classifier extract-reads \
  --i-sequences "$CLASSIFIER_RAW_SEQS" \
  --p-f-primer "$PRIMER_F" \
  --p-r-primer "$PRIMER_R" \
  --p-trunc-len 0 \
  --p-n-jobs 8 \
  --o-reads "$extracted_reads"

echo "Step 2/2: Fitting the naive Bayes classifier..."
qiime feature-classifier fit-classifier-naive-bayes \
  --i-reference-reads "$extracted_reads" \
  --i-reference-taxonomy "$CLASSIFIER_RAW_TAX" \
  --o-classifier "$CLASSIFIER_QZA"

echo "Done. Classifier saved to: $CLASSIFIER_QZA"
